import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { toast } from "sonner";
import { AppShell } from "@/components/app-shell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useOperations } from "@/lib/operations";

export const Route = createFileRoute("/achats-receptions")({ head: () => ({ meta: [{ title: "Achats & Réceptions — Habanera" }, { name: "description", content: "Enregistrement et suivi des livraisons de l'économat." }, { property: "og:title", content: "Achats & Réceptions — Habanera" }, { property: "og:description", content: "Suivez les commandes et réceptions Habanera." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Page });
function Page() { const { articles, purchases, addPurchase } = useOperations(); const [supplier,setSupplier]=useState("Atlas Distribution"); const [articleId,setArticleId]=useState(articles[0]?.id ?? ""); const [quantity,setQuantity]=useState(12); return <AppShell title="Achats & Réceptions" subtitle="Entrées de marchandises et bons de livraison"><div className="grid gap-5 xl:grid-cols-[360px_1fr]"><Card><CardHeader><CardTitle className="text-base">Enregistrer une livraison</CardTitle></CardHeader><CardContent className="space-y-4"><div><Label>Fournisseur</Label><Input value={supplier} onChange={(e)=>setSupplier(e.target.value)} /></div><div><Label>Produit</Label><Select value={articleId} onValueChange={setArticleId}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{articles.map((a)=><SelectItem key={a.id} value={a.id}>{a.nom}</SelectItem>)}</SelectContent></Select></div><div><Label>Quantité reçue</Label><Input type="number" min={1} value={quantity} onChange={(e)=>setQuantity(Number(e.target.value))}/></div><Button className="w-full" onClick={()=>{ if(!supplier.trim()||quantity<1)return; addPurchase({supplier,articleId,quantity,date:"23/09/2026",status:"Reçue"}); toast.success("Livraison enregistrée et stock mis à jour."); }}>Enregistrer la réception</Button></CardContent></Card><Card><CardContent className="p-5"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Référence</TableHead><TableHead>Fournisseur</TableHead><TableHead>Produit</TableHead><TableHead>Quantité</TableHead><TableHead>Date</TableHead><TableHead>Statut</TableHead></TableRow></TableHeader><TableBody>{purchases.map((p)=><TableRow key={p.id}><TableCell>{p.id}</TableCell><TableCell>{p.supplier}</TableCell><TableCell>{articles.find((a)=>a.id===p.articleId)?.nom}</TableCell><TableCell>{p.quantity}</TableCell><TableCell>{p.date}</TableCell><TableCell><Badge variant={p.status==="Reçue"?"secondary":"outline"}>{p.status}</Badge></TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card></div></AppShell> }