import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { toast } from "sonner";
import { AppShell } from "@/components/app-shell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { formatMAD } from "@/lib/habanera-data";
import { useOperations } from "@/lib/operations";
const suppliers=[{name:"Atlas Distribution",price:310,delay:1,quality:4.8,available:true},{name:"Maison des Vins",price:285,delay:5,quality:4.6,available:true},{name:"Comptoir Marrakech",price:298,delay:3,quality:4.2,available:false}];
export const Route=createFileRoute("/fournisseurs")({head:()=>({meta:[{title:"Fournisseurs & Recommandation — Habanera"},{name:"description",content:"Comparaison multicritère des fournisseurs Habanera."},{property:"og:title",content:"Fournisseurs & Recommandation — Habanera"},{property:"og:description",content:"Choisissez le fournisseur adapté à l'urgence."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Page});
function Page(){const{articles,addPurchase}=useOperations();const[articleId,setArticleId]=useState(articles.find((a)=>a.stock<a.seuil)?.id??articles[0]?.id??"");const[urgent,setUrgent]=useState("urgent");const ranked=[...suppliers].sort((a,b)=>urgent==="urgent"?a.delay-b.delay:a.price-b.price);return <AppShell title="Fournisseurs & Recommandation" subtitle="Décision multicritère selon l'urgence et la disponibilité"><Card className="mb-5"><CardHeader><CardTitle className="text-base">Besoin à couvrir</CardTitle></CardHeader><CardContent className="flex flex-col gap-3 sm:flex-row"><Select value={articleId} onValueChange={setArticleId}><SelectTrigger className="sm:w-72"><SelectValue/></SelectTrigger><SelectContent>{articles.map((a)=><SelectItem key={a.id} value={a.id}>{a.nom}</SelectItem>)}</SelectContent></Select><Select value={urgent} onValueChange={setUrgent}><SelectTrigger className="sm:w-48"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="urgent">Besoin urgent</SelectItem><SelectItem value="economique">Priorité au prix</SelectItem></SelectContent></Select></CardContent></Card><Card><CardContent className="p-5"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Fournisseur</TableHead><TableHead>Prix</TableHead><TableHead>Délai</TableHead><TableHead>Qualité</TableHead><TableHead>Disponibilité</TableHead><TableHead>Recommandation</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader><TableBody>{ranked.map((s,i)=><TableRow key={s.name}><TableCell className="font-medium">{s.name}</TableCell><TableCell>{formatMAD(s.price)}</TableCell><TableCell>{s.delay} j</TableCell><TableCell>{s.quality}/5</TableCell><TableCell><Badge variant={s.available?"secondary":"outline"}>{s.available?"Disponible":"Indisponible"}</Badge></TableCell><TableCell>{i===0?<Badge>Recommandé · {urgent==="urgent"?"Urgent":"Économique"}</Badge>:"Alternative"}</TableCell><TableCell className="text-right"><Button size="sm" disabled={!s.available} onClick={()=>{addPurchase({supplier:s.name,articleId,quantity:12,date:"24/09/2026",status:"En cours"});toast.success(`Commande pré-remplie auprès de ${s.name}.`);}}>Commander</Button></TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card></AppShell>}