import { createFileRoute } from "@tanstack/react-router";
import { Archive, Save, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { AppShell } from "@/components/app-shell";
import { DocumentPreview } from "@/components/document-preview";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { formatMAD } from "@/lib/habanera-data";
import { useOperations, type InventoryReport } from "@/lib/operations";
import type { OfficialDocument } from "@/lib/pdf";

export const Route = createFileRoute("/inventaire")({ head: () => ({ meta: [{ title: "Inventaire — Habanera" }, { name: "description", content: "Comparatif des stocks et démarque." }, { property: "og:title", content: "Inventaire — Habanera" }, { property: "og:description", content: "Sauvegarde, clôture et rapport d’inventaire." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Page });

function Page() {
  const { articles, updateArticle, inventoryReports, closeInventory, inventoryDraft, saveInventoryDraft } = useOperations();
  const [counts, setCounts] = useState<Record<string, number>>(() => inventoryDraft?.counts ?? Object.fromEntries(articles.map((article) => [article.id, article.stock])));
  const [search, setSearch] = useState(""); const [point, setPoint] = useState("Tous"); const [critical, setCritical] = useState("Tous"); const [document, setDocument] = useState<OfficialDocument | null>(null);
  const rows = useMemo(() => articles.filter((article) => article.nom.toLowerCase().includes(search.toLowerCase()) && (point === "Tous" || article.point === point) && (critical === "Tous" || Math.abs((counts[article.id] ?? article.stock) - article.stock) >= 3)), [articles, search, point, critical, counts]);
  function reportDoc(report: InventoryReport) { setDocument({ kind: "RAPPORT D’INVENTAIRE", reference: report.id, date: report.date, subtitle: "Clôture officielle de période", metadata: [["Responsable", report.author], ["Articles comptés", String(report.lines.length)]], columns: ["Produit", "Théorique", "Réel", "Écart", "Valeur"], rows: report.lines.map((line) => [line.article, `${line.theoretical} ${line.unit}`, `${line.real} ${line.unit}`, line.gap, formatMAD(line.value)]), total: `Impact financier : ${formatMAD(report.totalGap)}`, note: "Les écarts constatés sont transmis au suivi des anomalies." }); }
  function close() { const lines = articles.map((article) => { const real = counts[article.id] ?? article.stock; return { article: article.nom, theoretical: article.stock, real, gap: real - article.stock, value: (real - article.stock) * article.prixAchat, unit: article.unite }; }); const report = closeInventory({ date: new Date().toLocaleString("fr-FR"), author: "Salah Bennani", totalGap: lines.reduce((sum, line) => sum + line.value, 0), lines }); reportDoc(report); toast.success("Inventaire clôturé et rapport généré."); }
  return <AppShell title="Inventaire" subtitle={inventoryDraft ? `Dernier enregistrement : ${inventoryDraft.savedAt}` : "Comparatif théorique, réel et démarque"} action={<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => { saveInventoryDraft(counts, "Salah Bennani"); toast.success("Comptage en cours enregistré."); }}><Save className="mr-2 h-4 w-4" />Enregistrer</Button><Button onClick={close}><Archive className="mr-2 h-4 w-4" />Clôturer l’inventaire</Button></div>}>
    <Card className="mb-4"><CardContent className="grid gap-3 p-4 md:grid-cols-[1fr_180px_190px]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input className="pl-9" placeholder="Rechercher un produit" value={search} onChange={(event) => setSearch(event.target.value)} /></div><Select value={point} onValueChange={setPoint}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["Tous", "Bar", "Cuisine", "Économat"].map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select><Select value={critical} onValueChange={setCritical}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Tous">Tous les écarts</SelectItem><SelectItem value="Critiques">Écarts critiques</SelectItem></SelectContent></Select></CardContent></Card>
    <Card><CardContent className="overflow-x-auto p-5"><Table><TableHeader><TableRow><TableHead>Produit</TableHead><TableHead>Théorique</TableHead><TableHead>Stock réel</TableHead><TableHead>Écart</TableHead><TableHead>Valeur écart</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader><TableBody>{rows.map((article) => { const real = counts[article.id] ?? article.stock; const gap = real - article.stock; return <TableRow key={article.id}><TableCell className="font-medium">{article.nom}<p className="text-xs text-muted-foreground">{article.point}</p></TableCell><TableCell>{article.stock} {article.unite}</TableCell><TableCell><Input className="w-28" type="number" min={0} value={real} onChange={(event) => setCounts((current) => ({ ...current, [article.id]: Number(event.target.value) }))} /></TableCell><TableCell><Badge variant={gap === 0 ? "success" : Math.abs(gap) >= 3 ? "destructive" : "warning"}>{gap > 0 ? `+${gap}` : gap} {article.unite}</Badge></TableCell><TableCell className={gap < 0 ? "text-destructive" : "text-success"}>{formatMAD(gap * article.prixAchat)}</TableCell><TableCell className="text-right"><Button size="sm" variant="outline" disabled={gap === 0} onClick={() => { updateArticle(article.id, { stock: real }); toast.success(`Stock de ${article.nom} ajusté.`); }}>Ajuster le stock</Button></TableCell></TableRow>; })}</TableBody></Table></CardContent></Card>
    {inventoryReports.length > 0 && <section className="mt-6"><h2 className="mb-3 text-lg">Historique des clôtures</h2><div className="grid gap-3 md:grid-cols-3">{inventoryReports.map((report) => <Button key={report.id} variant="outline" onClick={() => reportDoc(report)} className="h-auto justify-start p-4 text-left"><span><span className="block font-medium">{report.id}</span><span className="block text-sm text-muted-foreground">{report.date}</span><span className="mt-2 block text-sm">Impact : {formatMAD(report.totalGap)}</span></span></Button>)}</div></section>}
    <DocumentPreview document={document} open={Boolean(document)} onOpenChange={(open) => { if (!open) setDocument(null); }} />
  </AppShell>;
}
