/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AchatsReceptionsRouteImport } from './routes/achats-receptions'
import { Route as AlertesRouteImport } from './routes/alertes'
import { Route as ApprovisionnementRouteImport } from './routes/approvisionnement'
import { Route as BonsPrelevementRouteImport } from './routes/bons-prelevement'
import { Route as ConfigurationRouteImport } from './routes/configuration'
import { Route as CuisineBarRouteImport } from './routes/cuisine-bar'
import { Route as EconomatRouteImport } from './routes/economat'
import { Route as FournisseursRouteImport } from './routes/fournisseurs'
import { Route as InventaireRouteImport } from './routes/inventaire'
import { Route as MonStockRouteImport } from './routes/mon-stock'
import { Route as MouvementsRouteImport } from './routes/mouvements'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as ReceptionsRouteImport } from './routes/receptions'
import { Route as ReportingRouteImport } from './routes/reporting'
import { Route as StockRouteImport } from './routes/stock'
import { Route as TableauDeBordRouteImport } from './routes/tableau-de-bord'
import { Route as UtilisateursRouteImport } from './routes/utilisateurs'
import { Route as VentesRouteImport } from './routes/ventes'
import { Route as VentesZRouteImport } from './routes/ventes-z'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchatsReceptionsRoute = AchatsReceptionsRouteImport.update({
  id: '/achats-receptions',
  path: '/achats-receptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertesRoute = AlertesRouteImport.update({
  id: '/alertes',
  path: '/alertes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovisionnementRoute = ApprovisionnementRouteImport.update({
  id: '/approvisionnement',
  path: '/approvisionnement',
  getParentRoute: () => rootRouteImport,
} as any)
const BonsPrelevementRoute = BonsPrelevementRouteImport.update({
  id: '/bons-prelevement',
  path: '/bons-prelevement',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationRoute = ConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const CuisineBarRoute = CuisineBarRouteImport.update({
  id: '/cuisine-bar',
  path: '/cuisine-bar',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomatRoute = EconomatRouteImport.update({
  id: '/economat',
  path: '/economat',
  getParentRoute: () => rootRouteImport,
} as any)
const FournisseursRoute = FournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => rootRouteImport,
} as any)
const InventaireRoute = InventaireRouteImport.update({
  id: '/inventaire',
  path: '/inventaire',
  getParentRoute: () => rootRouteImport,
} as any)
const MonStockRoute = MonStockRouteImport.update({
  id: '/mon-stock',
  path: '/mon-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const MouvementsRoute = MouvementsRouteImport.update({
  id: '/mouvements',
  path: '/mouvements',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionsRoute = ReceptionsRouteImport.update({
  id: '/receptions',
  path: '/receptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingRoute = ReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const TableauDeBordRoute = TableauDeBordRouteImport.update({
  id: '/tableau-de-bord',
  path: '/tableau-de-bord',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilisateursRoute = UtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const VentesRoute = VentesRouteImport.update({
  id: '/ventes',
  path: '/ventes',
  getParentRoute: () => rootRouteImport,
} as any)
const VentesZRoute = VentesZRouteImport.update({
  id: '/ventes-z',
  path: '/ventes-z',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achats-receptions': typeof AchatsReceptionsRoute
  '/alertes': typeof AlertesRoute
  '/approvisionnement': typeof ApprovisionnementRoute
  '/bons-prelevement': typeof BonsPrelevementRoute
  '/configuration': typeof ConfigurationRoute
  '/cuisine-bar': typeof CuisineBarRoute
  '/economat': typeof EconomatRoute
  '/fournisseurs': typeof FournisseursRoute
  '/inventaire': typeof InventaireRoute
  '/mon-stock': typeof MonStockRoute
  '/mouvements': typeof MouvementsRoute
  '/notifications': typeof NotificationsRoute
  '/parametres': typeof ParametresRoute
  '/receptions': typeof ReceptionsRoute
  '/reporting': typeof ReportingRoute
  '/stock': typeof StockRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/ventes': typeof VentesRoute
  '/ventes-z': typeof VentesZRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achats-receptions': typeof AchatsReceptionsRoute
  '/alertes': typeof AlertesRoute
  '/approvisionnement': typeof ApprovisionnementRoute
  '/bons-prelevement': typeof BonsPrelevementRoute
  '/configuration': typeof ConfigurationRoute
  '/cuisine-bar': typeof CuisineBarRoute
  '/economat': typeof EconomatRoute
  '/fournisseurs': typeof FournisseursRoute
  '/inventaire': typeof InventaireRoute
  '/mon-stock': typeof MonStockRoute
  '/mouvements': typeof MouvementsRoute
  '/notifications': typeof NotificationsRoute
  '/parametres': typeof ParametresRoute
  '/receptions': typeof ReceptionsRoute
  '/reporting': typeof ReportingRoute
  '/stock': typeof StockRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/ventes': typeof VentesRoute
  '/ventes-z': typeof VentesZRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achats-receptions': typeof AchatsReceptionsRoute
  '/alertes': typeof AlertesRoute
  '/approvisionnement': typeof ApprovisionnementRoute
  '/bons-prelevement': typeof BonsPrelevementRoute
  '/configuration': typeof ConfigurationRoute
  '/cuisine-bar': typeof CuisineBarRoute
  '/economat': typeof EconomatRoute
  '/fournisseurs': typeof FournisseursRoute
  '/inventaire': typeof InventaireRoute
  '/mon-stock': typeof MonStockRoute
  '/mouvements': typeof MouvementsRoute
  '/notifications': typeof NotificationsRoute
  '/parametres': typeof ParametresRoute
  '/receptions': typeof ReceptionsRoute
  '/reporting': typeof ReportingRoute
  '/stock': typeof StockRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/ventes': typeof VentesRoute
  '/ventes-z': typeof VentesZRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achats-receptions'
    | '/alertes'
    | '/approvisionnement'
    | '/bons-prelevement'
    | '/configuration'
    | '/cuisine-bar'
    | '/economat'
    | '/fournisseurs'
    | '/inventaire'
    | '/mon-stock'
    | '/mouvements'
    | '/notifications'
    | '/parametres'
    | '/receptions'
    | '/reporting'
    | '/stock'
    | '/tableau-de-bord'
    | '/utilisateurs'
    | '/ventes'
    | '/ventes-z'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achats-receptions'
    | '/alertes'
    | '/approvisionnement'
    | '/bons-prelevement'
    | '/configuration'
    | '/cuisine-bar'
    | '/economat'
    | '/fournisseurs'
    | '/inventaire'
    | '/mon-stock'
    | '/mouvements'
    | '/notifications'
    | '/parametres'
    | '/receptions'
    | '/reporting'
    | '/stock'
    | '/tableau-de-bord'
    | '/utilisateurs'
    | '/ventes'
    | '/ventes-z'
  id:
    | '__root__'
    | '/'
    | '/achats-receptions'
    | '/alertes'
    | '/approvisionnement'
    | '/bons-prelevement'
    | '/configuration'
    | '/cuisine-bar'
    | '/economat'
    | '/fournisseurs'
    | '/inventaire'
    | '/mon-stock'
    | '/mouvements'
    | '/notifications'
    | '/parametres'
    | '/receptions'
    | '/reporting'
    | '/stock'
    | '/tableau-de-bord'
    | '/utilisateurs'
    | '/ventes'
    | '/ventes-z'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchatsReceptionsRoute: typeof AchatsReceptionsRoute
  AlertesRoute: typeof AlertesRoute
  ApprovisionnementRoute: typeof ApprovisionnementRoute
  BonsPrelevementRoute: typeof BonsPrelevementRoute
  ConfigurationRoute: typeof ConfigurationRoute
  CuisineBarRoute: typeof CuisineBarRoute
  EconomatRoute: typeof EconomatRoute
  FournisseursRoute: typeof FournisseursRoute
  InventaireRoute: typeof InventaireRoute
  MonStockRoute: typeof MonStockRoute
  MouvementsRoute: typeof MouvementsRoute
  NotificationsRoute: typeof NotificationsRoute
  ParametresRoute: typeof ParametresRoute
  ReceptionsRoute: typeof ReceptionsRoute
  ReportingRoute: typeof ReportingRoute
  StockRoute: typeof StockRoute
  TableauDeBordRoute: typeof TableauDeBordRoute
  UtilisateursRoute: typeof UtilisateursRoute
  VentesRoute: typeof VentesRoute
  VentesZRoute: typeof VentesZRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achats-receptions': {
      id: '/achats-receptions'
      path: '/achats-receptions'
      fullPath: '/achats-receptions'
      preLoaderRoute: typeof AchatsReceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertes': {
      id: '/alertes'
      path: '/alertes'
      fullPath: '/alertes'
      preLoaderRoute: typeof AlertesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvisionnement': {
      id: '/approvisionnement'
      path: '/approvisionnement'
      fullPath: '/approvisionnement'
      preLoaderRoute: typeof ApprovisionnementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bons-prelevement': {
      id: '/bons-prelevement'
      path: '/bons-prelevement'
      fullPath: '/bons-prelevement'
      preLoaderRoute: typeof BonsPrelevementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration': {
      id: '/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof ConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuisine-bar': {
      id: '/cuisine-bar'
      path: '/cuisine-bar'
      fullPath: '/cuisine-bar'
      preLoaderRoute: typeof CuisineBarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economat': {
      id: '/economat'
      path: '/economat'
      fullPath: '/economat'
      preLoaderRoute: typeof EconomatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fournisseurs': {
      id: '/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/fournisseurs'
      preLoaderRoute: typeof FournisseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventaire': {
      id: '/inventaire'
      path: '/inventaire'
      fullPath: '/inventaire'
      preLoaderRoute: typeof InventaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-stock': {
      id: '/mon-stock'
      path: '/mon-stock'
      fullPath: '/mon-stock'
      preLoaderRoute: typeof MonStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mouvements': {
      id: '/mouvements'
      path: '/mouvements'
      fullPath: '/mouvements'
      preLoaderRoute: typeof MouvementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receptions': {
      id: '/receptions'
      path: '/receptions'
      fullPath: '/receptions'
      preLoaderRoute: typeof ReceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting': {
      id: '/reporting'
      path: '/reporting'
      fullPath: '/reporting'
      preLoaderRoute: typeof ReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tableau-de-bord': {
      id: '/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof TableauDeBordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilisateurs': {
      id: '/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof UtilisateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventes': {
      id: '/ventes'
      path: '/ventes'
      fullPath: '/ventes'
      preLoaderRoute: typeof VentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventes-z': {
      id: '/ventes-z'
      path: '/ventes-z'
      fullPath: '/ventes-z'
      preLoaderRoute: typeof VentesZRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchatsReceptionsRoute: AchatsReceptionsRoute,
  AlertesRoute: AlertesRoute,
  ApprovisionnementRoute: ApprovisionnementRoute,
  BonsPrelevementRoute: BonsPrelevementRoute,
  ConfigurationRoute: ConfigurationRoute,
  CuisineBarRoute: CuisineBarRoute,
  EconomatRoute: EconomatRoute,
  FournisseursRoute: FournisseursRoute,
  InventaireRoute: InventaireRoute,
  MonStockRoute: MonStockRoute,
  MouvementsRoute: MouvementsRoute,
  NotificationsRoute: NotificationsRoute,
  ParametresRoute: ParametresRoute,
  ReceptionsRoute: ReceptionsRoute,
  ReportingRoute: ReportingRoute,
  StockRoute: StockRoute,
  TableauDeBordRoute: TableauDeBordRoute,
  UtilisateursRoute: UtilisateursRoute,
  VentesRoute: VentesRoute,
  VentesZRoute: VentesZRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
